// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {todo} from '../models';

export function AddTask(arg1:string,arg2:string,arg3:string):Promise<todo.Task>;

export function DeleteTask(arg1:string):Promise<void>;

export function GetTasks():Promise<Array<todo.Task>>;

export function ToggleComplete(arg1:string):Promise<todo.Task>;
